steps:
- name: gcr.io/cloud-builders/git
  entrypoint: /usr/bin/find
  args: ['.']
- name: gcr.io/cloud-builders/git
  args: ['fetch', '--unshallow', '--tags']
- name: gcr.io/cloud-builders/docker
  entrypoint: make
  args:
    - REGISTRY_HOST=gcr.io
    - USERNAME=${PROJECT_ID}
    - snapshot
